classdef topsDataLogGUI < handle
    properties
        timeZero = 0;
        timeInterval = eps;
        
        fig;
        
        ignoredMnemonicsLabel;
        ignoredMnemonicsList;
        
        triggerMnemonicsLabel;
        triggerMnemonicsList;
        
        accumulatorAxes;
        accumulatorClearButton;
        
        dataLogAxes;
        dataLogReplayButton;
        dataLogLines;
        
        guiClearButton;
        
        listeners = struct();
    end
    
    methods
        function self = topsDataLogGUI()
            self.createWidgets;
            self.replayEntireLog;
            self.listenToDataLog;
        end
        function delete(self)
            if ~isempty(self.fig) && ishandle(self.fig);
                delete(self.fig);
            end
            delete(struct2array(self.listeners));
        end
        
        function replayEntireLog(self)
            cla(self.dataLogAxes)
            cla(self.accumulatorAxes);
            
            self.timeInterval = eps;
            self.dataLogLines = [];

            theLog = topsDataLog.theDataLog;
            entireLogStruct = theLog.getAllDataSorted;
            ed = EventWithData;
            for ii = 1:length(entireLogStruct)
                ed.UserData = entireLogStruct(ii);
                self.hearNewData(theLog, ed);
            end
        end
        
        function listenToDataLog(self)
            theLog = topsDataLog.theDataLog;
            
            delete(struct2array(self.listeners))
            self.listeners.NewMnemonic = theLog.addlistener( ...
                'NewMnemonic', ...
                @(source, event) self.hearNewMnemonic(source, event));
            self.listeners.NewData = theLog.addlistener( ...
                'NewData', ...
                @(source, event) self.hearNewData(source, event));
            self.listeners.FlushedTheDataLog = theLog.addlistener( ...
                'FlushedTheDataLog', ...
                @(source, event) self.hearFlushedTheDataLog(source, event));
        end
        
        function hearNewMnemonic(self, theLog, event)
            mnemonics = theLog.getAllMnemonics;
            insert = find(strcmp(mnemonics, event.UserData));
            set(self.ignoredMnemonicsList, 'String', mnemonics);
            set(self.triggerMnemonicsList, 'String', mnemonics);
            
            if length(mnemonics) > 1
                self.fixListSelectionsAfterInsert(self.ignoredMnemonicsList, insert);
                self.fixListSelectionsAfterInsert(self.triggerMnemonicsList, insert);
            end
        end
        
        function fixListSelectionsAfterInsert(self, list, insert)
            selected = get(list, 'Value');
            bump = selected >= insert;
            selected(bump) = selected(bump) + 1;
            set(list, 'Value', selected);
        end
        
        function hearNewData(self, theLog, eventData)
            logStruct = eventData.UserData;
            mnemonics = theLog.getAllMnemonics;
            
            trig = get(self.triggerMnemonicsList, 'Value');
            if ~isempty(trig)
                
                if any(strcmp(mnemonics(trig), logStruct.mnemonic))
                    % retrigger
                    self.trigger(logStruct);
                end
            else
                self.timeZero = theLog.earliestTime;
            end
            
            ignored = get(self.ignoredMnemonicsList, 'Value');
            if isempty(ignored) || ~any(strcmp(mnemonics(ignored), logStruct.mnemonic))
                self.plotLogEntry(logStruct);
            end
        end
        
        function trigger(self, logStruct)
            self.timeZero = logStruct.time;
            if ~isempty(self.dataLogLines)
                set(self.dataLogLines, 'Parent', self.accumulatorAxes);
            end
            self.dataLogLines = [];
            cla(self.dataLogAxes);
        end
        
        function plotLogEntry(self, logStruct)
            % adjust axes bounds for new data
            y = logStruct.time - self.timeZero;
            if y > self.timeInterval
                self.timeInterval = 2*y;
                set([self.dataLogAxes self.accumulatorAxes], ...
                    'YLim', [0 self.timeInterval+eps]);
            end
            
            % fudge a color for each mnemonic by BS hashing
            colNum = mod(sum(logStruct.mnemonic), 7);
            col = dec2bin(colNum, 3)=='1';
            
            summary = sprintf('%s: %s', ...
                logStruct.mnemonic, ...
                stringifyValue(logStruct.data));
            
            self.dataLogLines (end+1) = line([0 .1], [y y], ...
                'Parent', self.dataLogAxes, ...
                'Color', col, ...
                'LineStyle', '-', ...
                'Marker', 'none');
            
            text(.11, y, summary, ...
                'FontName', 'Courier', ...
                'HitTest', 'off', ...
                'Interpreter', 'none', ...
                'Parent', self.dataLogAxes, ...
                'Color', col, ....
                'VerticalAlignment', 'top', ...
                'HorizontalAlignment', 'left');
        end
        
        function hearFlushedTheDataLog(self, theLog, eventData)
            self.createWidgets;
        end
        
        function setupFigure(self)
            if ~isempty(self.fig) && ishandle(self.fig)
                clf(self.fig)
            else
                self.fig = figure;
            end
            set(self.fig, ...
                'CloseRequestFcn', @(obj, event) delete(self), ...
                'HandleVisibility', 'off', ...
                'MenuBar', 'none', ...
                'Name', mfilename, ...
                'NumberTitle', 'off', ...
                'ToolBar', 'none');
        end
        
        function createWidgets(self)
            self.setupFigure;
            
            self.timeInterval = eps;
            
            x = [.01 .3 .4 .41 .49 .5 .6 .7 .85 .89 .99];
            y = [.01 .45 .5 .94 .99];
            self.ignoredMnemonicsLabel = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'String', 'mnemonics to ignore', ...
                'Position', [x(1), y(4), x(3)-x(1), y(5)-y(4)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left');
            
            self.ignoredMnemonicsList = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'listbox', ...
                'Units', 'normalized', ...
                'String', topsDataLog.getAllMnemonics, ...
                'Position', [x(1), y(3), x(3)-x(1), y(4)-y(3)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left', ...
                'Value', [], ...
                'Min', 0, ...
                'Max', 1000);
            
            self.triggerMnemonicsLabel = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'String', 'mnemonics for trigger', ...
                'Position', [x(1), y(2), x(2)-x(1), y(3)-y(2)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left');
            
            self.triggerMnemonicsList = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'listbox', ...
                'Units', 'normalized', ...
                'String', topsDataLog.getAllMnemonics, ...
                'Position', [x(1), y(1), x(3)-x(1), y(2)-y(1)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left', ...
                'Value', [], ...
                'Min', 0, ...
                'Max', 1000);
            
            self.accumulatorAxes = axes( ...
                'Parent', self.fig, ...
                'Box', 'on', ...
                'Color', [1 1 1], ...
                'HitTest', 'off', ...
                'Position', [x(4), y(1), x(5)-x(4), y(4)-y(1)], ...
                'XTick', [], ...
                'XLim', [0 .1], ...
                'YTick', [], ...
                'YLim', [0 eps], ...
                'YDir', 'reverse');
            
            self.accumulatorClearButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'clear', ...
                'Callback', @(obj, event) cla(self.accumulatorAxes), ...
                'Position', [x(4), y(4), x(5)-x(4), y(5)-y(4)], ...
                'HorizontalAlignment', 'left');
            
            self.dataLogAxes = axes( ...
                'Parent', self.fig, ...
                'Box', 'off', ...
                'Color', [1 1 1], ...
                'HitTest', 'off', ...
                'Position', [x(6), y(1), x(11)-x(6), y(4)-y(1)], ...
                'XTick', [], ...
                'XLim', [0 1], ...
                'YTick', [], ...
                'YLim', [0 eps], ...
                'YDir', 'reverse');

            self.guiClearButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'clear', ...
                'Callback', @(obj, event) self.createWidgets, ...
                'Position', [x(6), y(4), x(7)-x(6), y(5)-y(4)], ...
                'HorizontalAlignment', 'left');
            
            self.dataLogReplayButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'replay log', ...
                'Callback', @(obj, event) self.replayEntireLog, ...
                'Position', [x(9), y(4), x(11)-x(9), y(5)-y(4)], ...
                'HorizontalAlignment', 'left');
        end
    end
end