classdef topsDataLogGUI < handle
    properties
        fig;
        
        shownMnemonicsLabel;
        shownMnemonicsList;
        
        triggerMnemonicsToggle;
        triggerMnemonicsLabel;
        triggerMnemonicsList;
        
        dataLogAxes;
        dataLogLines;
        dataLogTexts;
        dataLogPreviousLines;
        
        flushLogButton;
        refreshGUIButton;
        
        newMnemonicListener;
        newDataListener;
        flushedLogListener;
    end
    
    methods
        function self = topsDataLogGUI()
            self.createWidgets;
            self.listenToDataLog;
        end
        function delete(self)
            if ~isempty(self.fig) && ishandle(self.fig)
                close(self.fig)
            end
            
            delete(self.newMnemonicListener);
            delete(self.newDataListener);
            delete(self.flushedLogListener);
        end
        
        
        function createWidgets(self)
            self.setupFigure;
            
            w = [.48, .15];
            h = [.05, .44, .93];
            x = [.01, .34, .51, .84];
            y = cumsum([.01, h([2 1 2 1])]);
            
            self.shownMnemonicsLabel = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'String', 'mnemonics to display', ...
                'Position', [x(1), y(4), w(1), h(1)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left');
            
            self.shownMnemonicsList = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'listbox', ...
                'Units', 'normalized', ...
                'String', topsDataLog.getAllMnemonics, ...
                'Position', [x(1), y(3), w(1), h(2)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left', ...
                'Min', 0, ...
                'Max', 100);
            
            self.triggerMnemonicsLabel = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'String', 'mnemonics for trigger', ...
                'Position', [x(1), y(2), w(1), h(1)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left');
            
            self.triggerMnemonicsToggle = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'togglebutton', ...
                'Units', 'normalized', ...
                'String', 'trigger', ...
                'Position', [x(2), y(2), w(2), h(1)], ...
                'HorizontalAlignment', 'left');
            
            self.triggerMnemonicsList = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'listbox', ...
                'Units', 'normalized', ...
                'String', topsDataLog.getAllMnemonics, ...
                'Position', [x(1), y(1), w(1), h(2)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left', ...
                'Min', 0, ...
                'Max', 100);
            
            self.dataLogAxes = axes( ...
                'Parent', self.fig, ...
                'Box', 'on', ...
                'Color', [1 1 1], ...
                'HitTest', 'off', ...
                'Position', [x(3), y(1), w(1), h(3)], ...
                'XTick', [], ...
                'XLim', [0 1], ...
                'YTick', [], ...
                'YLim', [0 1]);
            
            self.flushLogButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'flush log', ...
                'Callback', @(obj, event) topsDataLog.flushAllData, ...
                'Position', [x(3), y(4), w(2), h(1)], ...
                'HorizontalAlignment', 'left');
            
            self.refreshGUIButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'refresh GUI', ...
                'Callback', @(obj, event) self.createWidgets, ...
                'Position', [x(4), y(4), w(2), h(1)], ...
                'HorizontalAlignment', 'left');
        end
        
        function listenToDataLog(self)
            theLog = topsDataLog.theDataLog;
            
            self.newMnemonicListener = theLog.addlistener( ...
                'newMnemonic', ...
                @(source, event) self.hearNewMnemonic(source, event));
            self.newDataListener = theLog.addlistener( ...
                'newDataForMnemonic', ...
                @(source, event) self.hearNewDataForMnemonic(source, event));
            self.flushedLogListener  = theLog.addlistener( ...
                'flushedTheDataLog', ...
                @(source, event) self.hearFlushedTheDataLog(source, event));
        end
        
        function hearNewMnemonic(self, theLog, eventData)
            
        end
        
        function hearNewDataForMnemonic(self, theLog, eventData)
            
        end
        
        function hearFlushedTheDataLog(self, theLog, eventData)
            self.createWidgets;
        end
        
        function setupFigure(self)
            if ~isempty(self.fig) && ishandle(self.fig)
                clf(self.fig)
            else
                self.fig = figure;
            end
            set(self.fig, ...
                'HandleVisibility', 'off', ...
                'MenuBar', 'none', ...
                'Name', mfilename, ...
                'NumberTitle', 'off', ...
                'ToolBar', 'none');
        end
    end
end