classdef topsDataLogGUI < handle
    properties
        zeroTime = nan;
        
        fig;
        
        shownMnemonicsLabel;
        shownMnemonicsList;
        
        triggerMnemonicsLabel;
        triggerMnemonicsList;
        triggerMnemonicsToggle;
        
        accumulatorAxes;
        accumulatorClearButton;
        
        dataLogAxes;
        dataLogFlushButton;
        dataLogLines;
        
        guiRefreshButton;
        
        listeners = struct();
    end
    
    methods
        function self = topsDataLogGUI()
            self.refreshAll;
            self.listenToDataLog;
        end
        function delete(self)
            if ~isempty(self.fig) && ishandle(self.fig);
                delete(self.fig);
            end
            delete(struct2array(self.listeners));
        end
        
        function createWidgets(self)
            self.setupFigure;
            
            x = [.01 .3 .4 .41 .49 .5 .6 .89 .99];
            y = [.01 .45 .5 .94 .99];
            self.shownMnemonicsLabel = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'String', 'mnemonics to display', ...
                'Position', [x(1), y(4), x(3)-x(1), y(5)-y(4)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left');
            
            self.shownMnemonicsList = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'listbox', ...
                'Units', 'normalized', ...
                'String', topsDataLog.getAllMnemonics, ...
                'Position', [x(1), y(3), x(3)-x(1), y(4)-y(3)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left', ...
                'Min', 0, ...
                'Max', 100);
            
            self.triggerMnemonicsLabel = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'String', 'mnemonics for trigger', ...
                'Position', [x(1), y(2), x(2)-x(1), y(3)-y(2)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left');
            
            self.triggerMnemonicsList = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'listbox', ...
                'Units', 'normalized', ...
                'String', topsDataLog.getAllMnemonics, ...
                'Position', [x(1), y(1), x(3)-x(1), y(2)-y(1)], ...
                'BackgroundColor', get(self.fig, 'Color'), ...
                'HorizontalAlignment', 'left', ...
                'Min', 0, ...
                'Max', 100);
            
            self.triggerMnemonicsToggle = uicontrol( ...
                'Parent', self.fig, ...
                'Style', 'togglebutton', ...
                'Units', 'normalized', ...
                'String', 'trigger', ...
                'Position', [x(2), y(2), x(3)-x(2), y(3)-y(2)], ...
                'HorizontalAlignment', 'left');
            
            self.accumulatorAxes = axes( ...
                'Parent', self.fig, ...
                'Box', 'on', ...
                'Color', [1 1 1], ...
                'HitTest', 'off', ...
                'Position', [x(4), y(1), x(5)-x(4), y(4)-y(1)], ...
                'XTick', [], ...
                'XLim', [0 .1], ...
                'YTick', [], ...
                'YLim', [0 1], ...
                'YDir', 'reverse');
            
            self.accumulatorClearButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'clear', ...
                'Callback', @(obj, event) cla(self.accumulatorAxes), ...
                'Position', [x(4), y(4), x(5)-x(4), y(5)-y(4)], ...
                'HorizontalAlignment', 'left');
            
            self.dataLogAxes = axes( ...
                'Parent', self.fig, ...
                'Box', 'on', ...
                'Color', [1 1 1], ...
                'HitTest', 'off', ...
                'Position', [x(6), y(1), x(9)-x(6), y(4)-y(1)], ...
                'XTick', [], ...
                'XLim', [0 1], ...
                'YTick', [], ...
                'YLim', [0 1], ...
                'YDir', 'reverse');
            self.dataLogLines = [];
            
            self.dataLogFlushButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'flush log', ...
                'Callback', @(obj, event) topsDataLog.flushAllData, ...
                'Position', [x(6), y(4), x(7)-x(6), y(5)-y(4)], ...
                'HorizontalAlignment', 'left');
            
            self.guiRefreshButton = uicontrol ( ...
                'Parent', self.fig, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'String', 'refresh', ...
                'Callback', @(obj, event) self.refreshAll, ...
                'Position', [x(8), y(4), x(9)-x(8), y(5)-y(4)], ...
                'HorizontalAlignment', 'left');
        end
        
        function setupFigure(self)
            if ~isempty(self.fig) && ishandle(self.fig)
                clf(self.fig)
            else
                self.fig = figure;
            end
            set(self.fig, ...
                'HandleVisibility', 'off', ...
                'MenuBar', 'none', ...
                'Name', mfilename, ...
                'NumberTitle', 'off', ...
                'ToolBar', 'none');
        end
        
        function refreshAll(self)
            self.createWidgets;
            self.replayEntireLog;
        end
        
        function listenToDataLog(self)
            theLog = topsDataLog.theDataLog;
            
            delete(struct2array(self.listeners))
            self.listeners.NewMnemonic = theLog.addlistener( ...
                'NewMnemonic', ...
                @(source, event) self.hearNewMnemonic(source, event));
            self.listeners.NewData = theLog.addlistener( ...
                'NewData', ...
                @(source, event) self.hearNewData(source, event));
            self.listeners.FlushedTheDataLog = theLog.addlistener( ...
                'FlushedTheDataLog', ...
                @(source, event) self.hearFlushedTheDataLog(source, event));
        end
        
        function hearNewMnemonic(self, theLog, event)
            mnemonics = theLog.getAllMnemonics;
            insert = find(strcmp(mnemonics, event.UserData));
            set(self.shownMnemonicsList, 'String', mnemonics);
            set(self.triggerMnemonicsList, 'String', mnemonics);
            
            if length(mnemonics) > 1
                self.fixListSelectionsAfterInsert(self.shownMnemonicsList, insert);
                self.fixListSelectionsAfterInsert(self.triggerMnemonicsList, insert);
            end
        end
        
        function fixListSelectionsAfterInsert(self, list, insert)
            selected = get(list, 'Value');
            bump = selected >= insert;
            selected(bump) = selected(bump) + 1;
            set(list, 'Value', selected);
        end
        
        function hearNewData(self, theLog, eventData)
            logStruct = eventData.UserData;
            mnemonics = theLog.getAllMnemonics;

            if get(self.triggerMnemonicsToggle, 'Value')
                % reset zero time for new data
                trig = get(self.triggerMnemonicsList, 'Value');
                if any(strcmp(mnemonics(trig), logStruct.mnemonic))
                    self.trigger(logStruct);
                end
            else
                % use overall zero time
                self.zeroTime = theLog.earliestTime;
            end
            
            show = get(self.shownMnemonicsList, 'Value');
            if any(strcmp(mnemonics(show), logStruct.mnemonic))
                self.plotLogEntry(logStruct);
            end
        end
        
        function trigger(self, logStruct)
            self.zeroTime = logStruct.time;
            if ~isempty(self.dataLogLines)
                set(self.dataLogLines, 'Parent', self.accumulatorAxes);
            end
            self.dataLogLines = [];
            cla(self.dataLogAxes);
        end
        
        function plotLogEntry(self, logStruct)
            
            % adjust axes bounds for new data
            set([self.dataLogAxes self.accumulatorAxes], ...
                'YLim', [0 logStruct.time-self.zeroTime+eps]);
            
            % fudge a color for each mnemonic by BS hashing
            colNum = mod(sum(logStruct.mnemonic), 7);
            col = dec2bin(colNum, 3)=='1';
            
            summary = sprintf('%s: %s', ...
                logStruct.mnemonic, ...
                stringifyValue(logStruct.data));
            
            y = logStruct.time - self.zeroTime;
            
            self.dataLogLines (end+1) = line([0 .1], [y y], ...
                'Parent', self.dataLogAxes, ...
                'Color', col, ...
                'LineStyle', '-', ...
                'Marker', 'none');
            
            text(.11, y, summary, ...
                'FontName', 'Courier', ...
                'HitTest', 'off', ...
                'Interpreter', 'none', ...
                'Parent', self.dataLogAxes, ...
                'Color', col);
        end
        
        function hearFlushedTheDataLog(self, theLog, eventData)
            self.createWidgets;
        end
        
        function replayEntireLog(self)
            entireLogStruct = topsDataLog.getAllDataSorted;
            ed = EventWithData;
            for ii = 1:length(entireLogStruct)
                ed.UserData = entireLogStruct(ii);
                self.hearNewData(topsDataLog.theDataLog, ed);
            end
        end
    end
end