close all
clear
clear classes

lookFeel = { ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [.9 .5 .1], ...
    'FontWeight', 'bold', ...
    'Callback', @(obj, event)disp(get(obj, 'String'))};

args = topsText.staticText;
more = { ...
    'String', 'static', ...
    'Units', 'normalized', ...
    'Position', subposition([0 0 1 1], 10, 3, 1, 2), ...
    };
static = uicontrol(args{:}, lookFeel{:}, more{:});

args = topsText.clickText;
more = { ...
    'String', 'click', ...
    'Units', 'normalized', ...
    'Position', subposition([0 0 1 1], 10, 3, 3, 2), ...
    };
click = uicontrol(args{:}, lookFeel{:}, more{:});

args = topsText.toggleText;
more = { ...
    'String', 'toggle', ...
    'Units', 'normalized', ...
    'Position', subposition([0 0 1 1], 10, 3, 5, 2), ...
    };
toggle = uicontrol(args{:}, lookFeel{:}, more{:});

args = topsText.editText;
more = { ...
    'String', 'edit', ...
    'Units', 'normalized', ...
    'Position', subposition([0 0 1 1], 10, 3, 7, 2), ...
    };
edit = uicontrol(args{:}, lookFeel{:}, more{:});